import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, FlaskConical, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRepScoringAdmin } from "@/lib/rep-scoring/access";
import { getV62CalibrationData, type V6Assessment } from "@/lib/rep-scoring/v6-calibration";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "V6.2 Final Calibration | Magic Mike Bot", robots: { index: false, follow: false } };

export default async function V62CalibrationPage() {
  await requireRepScoringAdmin();
  const data = await getV62CalibrationData();
  const calls = data.assessments;
  const call1 = calls.filter((call) => call.callType === "Call 1");
  const call2 = calls.filter((call) => call.callType === "Call 2+");
  const selectiveReviews = calls.filter((call) => call.materialReviewRequired).length;
  const complete = call1.length === 6 && call2.length === 6;
  const scores = calls.flatMap((call) => call.score === null ? [] : [call.score]);
  const range = scores.length ? `${Math.min(...scores).toFixed(1)}–${Math.max(...scores).toFixed(1)}` : "Pending";

  return <main className="magic-page"><div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-5 pb-16 pt-8 sm:px-8">
    <header className="magic-card magic-hero p-6 md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-4xl"><div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline" className="gap-1 rounded-full border-red-100 bg-red-50 text-red-700"><ShieldCheck className="size-3.5" />Admin only</Badge><Badge variant="outline" className="gap-1 rounded-full border-violet-200 bg-violet-50 text-violet-800"><FlaskConical className="size-3.5" />V6.2 final calibration</Badge></div><h1 className="text-4xl font-extrabold text-slate-950 md:text-5xl">One score per call, extra review only when needed</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">Each call receives one evidence-bound AI assessment. Code calculates the score and outcome; a short second verification runs only for a material risk, contradiction, or transcript limitation.</p></div><div className="flex flex-wrap gap-2"><Link href="/manager/rep-scoring/v6-1-calibration" className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Preserved V6.1 <ArrowRight className="size-4" /></Link><Link href="/manager/rep-scoring" className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Current manager view <ArrowRight className="size-4" /></Link></div></div></header>
    <div className={`rounded-2xl border p-5 text-sm leading-6 ${complete ? "border-emerald-200 bg-emerald-50 text-emerald-950" : "border-amber-200 bg-amber-50 text-amber-950"}`}><div className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0" /><div><strong>{complete ? "All 12 final calibration calls are ready for your review." : "The exact 12-call calibration is processing."}</strong> This is isolated from the manager production view, Coaching, schedules, and backfill.</div></div></div>
    {data.error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-950"><strong>Could not load V6.2 data:</strong> {data.error}</div> : null}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Calls ready" value={`${calls.length}/12`} detail="Exactly six Call 1 and six Call 2" /><Metric label="Selective reviews" value={`${selectiveReviews}/${calls.length || 12}`} detail="Second AI used only behind the material-risk gate" /><Metric label="Single-review calls" value={`${Math.max(0, calls.length - selectiveReviews)}`} detail="No duplicate AI judgment" /><Metric label="Score range" value={range} detail="Deterministically calculated, not model-selected" /></section>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-700"><strong>Cost model:</strong> one primary request for every call, plus a short verifier only for gated exceptions. JSON repair is invoked only if a model response is malformed. No ordinary call is double-scored.</div>
    <CalibrationSection title="Call 1 — fit and progression" description="Disposition is mapped consistently from the supported opportunity classification. A fair decline can score strongly." calls={call1} />
    <CalibrationSection title="Call 2 — execution and factual outcome" description="Sale, deposit, and concrete follow-up labels come from validated transaction and follow-up facts, not a free-form label." calls={call2} />
    <footer className="text-xs leading-5 text-slate-500">Loaded {formatDateTime(data.generatedAt)} · V6.1 and V6 remain preserved rollback paths.</footer>
  </div></main>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card className="magic-card border-white/80 bg-white/95"><CardContent className="p-5"><div className="text-3xl font-extrabold text-slate-950">{value}</div><div className="mt-1 font-bold text-slate-800">{label}</div><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></CardContent></Card>; }
function CalibrationSection({ title, description, calls }: { title: string; description: string; calls: V6Assessment[] }) { return <Card className="magic-card border-white/80 bg-white/95"><CardHeader className="gap-1"><CardTitle className="text-2xl text-slate-950">{title}</CardTitle><p className="text-sm leading-6 text-slate-500">{description}</p></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2">{calls.length ? calls.sort((a, b) => (a.score ?? 999) - (b.score ?? 999)).map((call) => <CallCard key={call.assessmentId} call={call} />) : <p className="col-span-full rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Results are still processing.</p>}</CardContent></Card>; }
function CallCard({ call }: { call: V6Assessment }) { const action = call.callType === "Call 1" ? call.disposition : call.outcome; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-extrabold text-slate-950">{call.repName}</h2><p className="mt-1 text-xs text-slate-500">{formatDateTime(call.meetingStartAt)}{call.showName ? ` · ${call.showName}` : ""}</p></div><div className="text-right"><div className="text-3xl font-extrabold text-slate-950">{call.score === null ? "—" : call.score.toFixed(1)}</div><div className="text-xs text-slate-500">{call.band}</div></div></div><div className="mt-4 flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full">{humanize(call.gradeability)}</Badge><Badge variant="outline" className="rounded-full border-blue-200 bg-blue-50 text-blue-800">{call.callType === "Call 1" ? "Disposition" : "Outcome"}: {humanize(action || "unknown")}</Badge><Badge variant="outline" className={`rounded-full ${call.materialReviewRequired ? "border-amber-200 bg-amber-50 text-amber-900" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{call.materialReviewRequired ? "Selective verifier used" : "Single AI assessment"}</Badge></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Main finding</div><p className="mt-2 text-sm font-semibold leading-6 text-slate-800">{call.mainFinding}</p></div><Link href={`/manager/rep-scoring/v6-2-calibration/call/${encodeURIComponent(call.sourceRecordId)}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-red-700">Review criteria and evidence <ArrowRight className="size-4" /></Link></article>; }
function humanize(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDateTime(value: string) { if (!value) return "Date unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "America/New_York" }).format(date); }
