const {test}=require('node:test'),assert=require('node:assert/strict'),{prepare,apply}=require('./apply.cjs');
const build={transcript:'[00:00:01.000] Rep: Would you proceed if approved?\n[00:00:02.000] Client: Yes.\n[00:00:03.000] Rep: Thank you.',metadata:{rep_name:'Rep'}};
function fixture(){return {raw:{parsed_json:{rudys_note:'Immutable coaching',manager_score:{dimensions:{frame_and_control:{band:'adequate',reason:'Clear opening'}},close_signals:{direct_commitment_ask:{present:true}},critical_events:[],review:{reason:'Real conversation'}}}},audit:{claims:[{id:'dimension.frame_and_control',kind:'text',text:'Clear opening'},{id:'signal.direct_commitment_ask',kind:'boolean',draft_value:true}],checks:[{id:'dimension.frame_and_control',status:'supported',evidence_ids:['T0001'],counterevidence_ids:[],verified_value:null,corrected_text:null},{id:'signal.direct_commitment_ask',status:'supported',evidence_ids:['T0001'],counterevidence_ids:[],verified_value:true,corrected_text:null}]}};}
test('supported audit preserves band, wording, coaching and input',()=>{let {raw,audit}=fixture();let before=JSON.stringify(raw),out=apply(raw,build,audit,{dimensions:[],signals:[],events:[],review_reason:null});assert.equal(JSON.stringify(raw),before);assert.equal(out.parsed_json.rudys_note,'Immutable coaching');assert.equal(out.parsed_json.manager_score.dimensions.frame_and_control.band,'adequate');assert.equal(out.parsed_json.manager_score.dimensions.frame_and_control.reason,'Clear opening');});
test('reassessment cannot change supported dimension',()=>{let {raw,audit}=fixture();assert.throws(()=>apply(raw,build,audit,{dimensions:[{name:'frame_and_control',band:'exemplary'}]}),/unapproved/);});
test('duplicate checks cannot conceal an unchecked claim',()=>{let {raw,audit}=fixture();audit.checks[1]=audit.checks[0];assert.throws(()=>prepare(raw,build,audit),/duplicate/);});
test('unknown references fail closed',()=>{let {raw,audit}=fixture();audit.checks[0].evidence_ids=['T9999'];assert.throws(()=>prepare(raw,build,audit),/Unknown transcript/);});
test('supported boolean cannot silently flip truth value',()=>{let {raw,audit}=fixture();audit.checks[1].verified_value=false;const p=prepare(raw,build,audit);assert.equal(p.manager.close_signals.direct_commitment_ask.present,true);assert.deepEqual(p.affected_dimensions,['close_mechanics_and_momentum']);});
test('contradicted claim marks only its affected dimension',()=>{let {raw,audit}=fixture();Object.assign(audit.checks[0],{status:'contradicted',corrected_text:'Opening was unclear'});assert.deepEqual(prepare(raw,build,audit).affected_dimensions,['frame_and_control']);});
test('reassessment cannot add a new critical event',()=>{let {raw,audit}=fixture();assert.throws(()=>apply(raw,build,audit,{dimensions:[],signals:[],events:[{index:0,retain:true}]}),/Unauthorized event/);});
test('prospect acceptance cannot be substituted for rep request',()=>{let {raw,audit}=fixture();audit.checks[1].evidence_ids=['T0002'];assert.throws(()=>prepare(raw,build,audit),/not rep speech/);});
test('rejected proposed correction cannot regrade or rewrite its associated dimension',()=>{let {raw,audit}=fixture();raw.parsed_json.manager_score.dimensions.close_mechanics_and_momentum={band:'adequate',reason:'Original close'};audit.checks[1].status='contradicted';audit.checks[1].verified_value=false;let out=apply(raw,build,audit,{dimensions:[{name:'close_mechanics_and_momentum',band:'exemplary',reason:'Unapproved rewrite',evidence_id:'T0001',counterevidence_ids:[]}],signals:[],events:[],review_reason:null,decisions:[{claim_id:'signal.direct_commitment_ask',accepted:false,explanation:'Original ask is supported'}]});assert.equal(out.parsed_json.manager_score.dimensions.close_mechanics_and_momentum.band,'adequate');assert.equal(out.parsed_json.manager_score.dimensions.close_mechanics_and_momentum.reason,'Original close');});
