import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink, Quote, ShieldAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRepScoringAdmin } from "@/lib/rep-scoring/access";
import { getV6CalibrationData, type V6Assessment, type V6Dimension, type V6Evidence, type V6Finding } from "@/lib/rep-scoring/v6-calibration";
import { cn } from "@/lib/utils";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "V6 Calibration Evidence | Magic Mike Bot", robots: { index: false, follow: false } };
type PageProps = { params: Promise<{ sourceRecordId: string }> };

export default async function V6CalibrationCallPage({ params }: PageProps) {
  await requireRepScoringAdmin();
  const { sourceRecordId } = await params;
  const data = await getV6CalibrationData();
  const pair = data.pairs.find((candidate) => candidate.sourceRecordId === decodeURIComponent(sourceRecordId));
  if (!pair) notFound();
  const call = pair.representative;
  return <main className="magic-page"><div className="mx-auto flex w-full max-w-6xl flex-col gap-5 px-5 pb-16 pt-8 sm:px-8">
    <Link href="/manager/rep-scoring/v6-calibration" className="inline-flex w-fit items-center gap-2 text-sm font-semibold text-slate-600 hover:text-red-700"><ArrowLeft className="size-4" />Back to V6 calibration</Link>
    <header className="magic-card magic-hero p-6 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><div className="mb-3 flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full border-violet-200 bg-violet-50 text-violet-800">V6 calibration</Badge><Badge variant="outline" className="rounded-full">{call.callType}</Badge></div><h1 className="text-4xl font-extrabold text-slate-950">{call.repName}</h1><p className="mt-2 text-sm text-slate-500">{formatDateTime(call.meetingStartAt)}{call.showName ? ` · ${call.showName}` : ""}</p></div><div className="grid grid-cols-2 gap-3"><ScoreBox label="Round 1" assessment={pair.round1} /><ScoreBox label="Round 2" assessment={pair.round2} /></div></div></header>
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><div className="flex gap-3"><ShieldAlert className="mt-0.5 size-5 shrink-0" /><div><strong>Human approval required.</strong> V6 remains calibration-only. A difference above 10 points or a band change is explicitly marked for review; no backfill or Coaching score is released from this page.</div></div></div>
    <section className="grid gap-5 lg:grid-cols-3"><SummaryCard title="Transcript" value={humanize(call.gradeability)} text={call.reliabilityReason || "No reliability explanation returned."} /><SummaryCard title="Prospect opportunity" value={humanize(call.opportunity)} text={call.opportunityReason || "No opportunity explanation returned."} /><SummaryCard title={call.callType === "Call 2+" ? "Actual outcome" : "Correct disposition"} value={humanize(call.callType === "Call 2+" ? call.outcome : call.disposition || "unknown")} text={call.callType === "Call 2+" ? call.outcomeReason : "The progression decision is judged against prospect fit, not whether every lead advanced."} /></section>
    <RoundReview title="Round 1" assessment={pair.round1} />
    <RoundReview title="Round 2" assessment={pair.round2} />
    <div className="flex flex-wrap items-center gap-3">{call.transcriptUrl ? <a href={call.transcriptUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:border-red-200 hover:text-red-700">Open source transcript <ExternalLink className="size-4" /></a> : null}<span className="text-xs text-slate-500">Source call: {pair.sourceRecordId}</span></div>
  </div></main>;
}

function ScoreBox({ label, assessment }: { label: string; assessment: V6Assessment | null }) { return <div className="rounded-2xl border border-slate-200 bg-white/90 px-5 py-4 text-right"><div className="text-xs font-bold text-slate-500">{label}</div><div className="text-3xl font-extrabold text-slate-950">{assessment?.score === null || assessment?.score === undefined ? "—" : assessment.score.toFixed(1)}</div><div className="mt-1 text-xs text-slate-500">{assessment?.band || "Pending"}</div></div>; }
function SummaryCard({ title, value, text }: { title: string; value: string; text: string }) { return <Card className="magic-card border-white/80 bg-white/95"><CardHeader className="gap-2"><CardTitle className="text-lg text-slate-950">{title}</CardTitle><Badge variant="outline" className="w-fit rounded-full">{value}</Badge></CardHeader><CardContent><p className="text-sm leading-6 text-slate-600">{text}</p></CardContent></Card>; }
function RoundReview({ title, assessment }: { title: string; assessment: V6Assessment | null }) { if (!assessment) return <Card className="magic-card border-amber-100 bg-amber-50/60"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="text-sm text-amber-900">This round has not finished.</CardContent></Card>; return <Card className="magic-card border-white/80 bg-white/95"><CardHeader className="gap-2"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-2xl text-slate-950">{title}: {assessment.score?.toFixed(1) ?? "—"}</CardTitle><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-700">{assessment.mainFinding}</p></div><Badge variant="outline" className="rounded-full">{assessment.band}</Badge></div></CardHeader><CardContent className="grid gap-5"><div className="grid gap-4">{assessment.dimensions.map((dimension) => <DimensionCard key={dimension.key} dimension={dimension} />)}</div><section className="grid gap-4 lg:grid-cols-3"><FindingList title="Strengths" findings={assessment.strengths} empty="No strength was forced." tone="green" /><FindingList title="Improvements" findings={assessment.improvements} empty="No improvement was forced." tone="amber" /><FindingList title="Critical findings" findings={assessment.criticalFindings} empty="No critical finding was verified." tone="red" /></section>{assessment.validationWarnings.length ? <div className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Excluded or limited dimensions:</strong><ul className="mt-2 list-disc pl-5">{assessment.validationWarnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div> : null}<details className="text-xs text-slate-500"><summary className="cursor-pointer font-semibold">Technical audit details</summary><div className="mt-2 rounded-xl bg-slate-950 p-3 font-mono leading-5 text-slate-200">Assessment: {assessment.assessmentId}<br />Scorer: {assessment.scorerVersion}<br />Validation: {assessment.validationStatus}<br />JSON repair: {assessment.repairAttempted ? "yes" : "no"}<br />Finalized: {formatDateTime(assessment.scoredAt)}</div></details></CardContent></Card>; }
function DimensionCard({ dimension }: { dimension: V6Dimension }) { const style = dimension.rating === "exceptional" || dimension.rating === "strong" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : dimension.rating === "partial" || dimension.rating === "weak" || dimension.rating === "harmful_or_absent" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-slate-200 bg-slate-50 text-slate-700"; return <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-extrabold text-slate-950">{dimension.label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{dimension.reason || "No explanation returned."}</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full">{humanize(dimension.applicability)}</Badge><Badge variant="outline" className={cn("rounded-full", style)}>{humanize(dimension.rating)}{dimension.points !== null ? ` · ${dimension.points}` : ""}</Badge>{dimension.weight !== null ? <Badge variant="outline" className="rounded-full">{Math.round(dimension.weight * 100)}% weight</Badge> : null}</div></div><div className="mt-4 grid gap-3">{dimension.evidence.map((evidence, index) => <EvidenceBlock key={`${evidence.timestamp}-${index}`} evidence={evidence} />)}{dimension.counterevidence.length ? <div className="mt-2"><div className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Counterevidence</div>{dimension.counterevidence.map((evidence, index) => <EvidenceBlock key={`${evidence.timestamp}-${index}`} evidence={evidence} />)}</div> : null}</div></article>; }
function FindingList({ title, findings, empty, tone }: { title: string; findings: V6Finding[]; empty: string; tone: "green" | "amber" | "red" }) { const style = tone === "green" ? "bg-emerald-50/60" : tone === "amber" ? "bg-amber-50/60" : "bg-red-50/60"; return <div className={cn("rounded-2xl p-4", style)}><h3 className="font-extrabold text-slate-950">{title}</h3><div className="mt-3 grid gap-3">{findings.length ? findings.map((finding, index) => <div key={`${finding.label}-${index}`} className="rounded-xl bg-white p-3"><div className="font-bold text-slate-900">{finding.label}</div>{finding.reason ? <p className="mt-1 text-sm leading-6 text-slate-600">{finding.reason}</p> : null}</div>) : <p className="text-sm text-slate-600">{empty}</p>}</div></div>; }
function EvidenceBlock({ evidence }: { evidence: V6Evidence }) { return <blockquote className="mt-3 rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-700"><div className="mb-2 flex flex-wrap items-center gap-2 text-xs font-semibold text-slate-500">{evidence.timestamp ? <Badge variant="outline" className="rounded-full bg-white">{evidence.timestamp}</Badge> : null}{evidence.speaker ? <span>{evidence.speaker}</span> : null}</div><div className="flex gap-2"><Quote className="mt-1 size-4 shrink-0 text-red-500" /><span className="italic">{evidence.quote}</span></div></blockquote>; }
function humanize(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDateTime(value: string) { if (!value) return "Not available"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "America/New_York" }).format(date); }
