import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, FlaskConical, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRepScoringAdmin } from "@/lib/rep-scoring/access";
import { getV61CalibrationData, type V6CalibrationPair } from "@/lib/rep-scoring/v6-calibration";
import { cn } from "@/lib/utils";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "V6.1 Calibration | Magic Mike Bot", robots: { index: false, follow: false } };

export default async function V61CalibrationPage() {
  await requireRepScoringAdmin();
  const data = await getV61CalibrationData();
  const call1 = data.pairs.filter((pair) => pair.representative.callType === "Call 1");
  const call2 = data.pairs.filter((pair) => pair.representative.callType === "Call 2+");
  const completePairs = data.pairs.filter((pair) => pair.round1 && pair.round2).length;
  const scoreStable = data.pairs.filter((pair) => pair.stable === true).length;
  const actionStable = data.pairs.filter((pair) => pair.actionStable === true).length;
  const decisionsAgree = data.pairs.filter((pair) => pair.outcomeMatch === true).length;
  const criticalDecisionsAgree = data.pairs.filter((pair) => pair.criticalMatch === true).length;
  const ready = call1.length === 6 && call2.length === 6 && completePairs === 12;
  const releaseGate = ready && actionStable >= 11 && decisionsAgree === 12 && criticalDecisionsAgree === 12;

  return <main className="magic-page"><div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-5 pb-16 pt-8 sm:px-8">
    <header className="magic-card magic-hero p-6 md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-4xl"><div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline" className="gap-1 rounded-full border-red-100 bg-red-50 text-red-700"><ShieldCheck className="size-3.5" />Admin only</Badge><Badge variant="outline" className="gap-1 rounded-full border-violet-200 bg-violet-50 text-violet-800"><FlaskConical className="size-3.5" />V6.1 criteria-first calibration</Badge></div><h1 className="text-4xl font-extrabold text-slate-950 md:text-5xl">Same 12 calls, stricter consistency check</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">Two complete judgments classify the same script-derived criteria with exact evidence. Deterministic code reconciles ordinary disagreement and calculates every score.</p></div><div className="flex flex-wrap gap-2"><Link href="/manager/rep-scoring/v6-calibration" className="inline-flex w-fit items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:border-red-200 hover:text-red-700">Preserved V6 <ArrowRight className="size-4" /></Link><Link href="/manager/rep-scoring" className="inline-flex w-fit items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:border-red-200 hover:text-red-700">Current manager view <ArrowRight className="size-4" /></Link></div></div></header>

    <div className={cn("rounded-2xl border p-5 text-sm leading-6", releaseGate ? "border-emerald-200 bg-emerald-50 text-emerald-950" : "border-amber-200 bg-amber-50 text-amber-950")}><div className="flex gap-3">{releaseGate ? <CheckCircle2 className="mt-0.5 size-5 shrink-0" /> : <AlertTriangle className="mt-0.5 size-5 shrink-0" />}<div><strong>{releaseGate ? "The automated calibration gate passed; your review is still required." : ready ? "All results are ready, but at least one consistency gate still needs review." : "The exact 12-call rerun is still processing."}</strong> {data.pairs.length} of 12 calls are visible and {completePairs} have both rounds. V6.1 remains calibration-only: no backfill and no Coaching score release.</div></div></div>
    {data.error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-950"><strong>Could not load V6.1 data:</strong> {data.error}</div> : null}

    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Unique calls" value={`${data.pairs.length}/12`} detail="The exact V6 sample" /><Metric label="Double-scored" value={`${completePairs}/12`} detail="Two independent runs" /><Metric label="Score stable" value={`${scoreStable}/${completePairs}`} detail="Same band and at most 10 points apart" /><Metric label="Action stable" value={`${actionStable}/${completePairs}`} detail="Score, outcome, and critical flag agree" /><Metric label="Backfill" value="Not started" detail="Requires your approval" /></section>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-700"><strong>Approval target:</strong> Call 1 dispositions, Call 2 outcomes, and critical flags must agree on all 12 calls; at least 11 of 12 must have the same manager action/band; no unexplained score difference may exceed 10 points.</div>
    <CalibrationSection title="Call 1 — fit and progression" description="A fair decline can score strongly when it is the correct decision for the prospect." pairs={call1} />
    <CalibrationSection title="Call 2 — value, objections, terms, and outcome" description="A sale is recorded separately. Transaction steps are not penalized before the prospect reaches that stage." pairs={call2} />
    <footer className="text-xs leading-5 text-slate-500">Loaded {formatDateTime(data.generatedAt)} · V6 and V5 remain preserved rollback paths.</footer>
  </div></main>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card className="magic-card border-white/80 bg-white/95"><CardContent className="p-5"><div className="text-3xl font-extrabold text-slate-950">{value}</div><div className="mt-1 font-bold text-slate-800">{label}</div><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></CardContent></Card>; }
function CalibrationSection({ title, description, pairs }: { title: string; description: string; pairs: V6CalibrationPair[] }) { return <Card className="magic-card border-white/80 bg-white/95"><CardHeader className="gap-1"><CardTitle className="text-2xl text-slate-950">{title}</CardTitle><p className="text-sm leading-6 text-slate-500">{description}</p></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2">{pairs.length ? pairs.map((pair) => <CalibrationCard key={pair.sourceRecordId} pair={pair} />) : <p className="col-span-full rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No V6.1 results are available for this call type yet.</p>}</CardContent></Card>; }
function CalibrationCard({ pair }: { pair: V6CalibrationPair }) { const call = pair.representative; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-extrabold text-slate-950">{call.repName}</h2><p className="mt-1 text-xs text-slate-500">{formatDateTime(call.meetingStartAt)}{call.showName ? ` · ${call.showName}` : ""}</p></div><StabilityBadge pair={pair} /></div><div className="mt-4 grid grid-cols-2 gap-3"><RoundScore label="Round 1" score={pair.round1?.score ?? null} band={pair.round1?.band} /><RoundScore label="Round 2" score={pair.round2?.score ?? null} band={pair.round2?.band} /></div><div className="mt-4 flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full">{humanize(call.gradeability)}</Badge><Badge variant="outline" className="rounded-full border-blue-200 bg-blue-50 text-blue-800">Prospect: {humanize(call.opportunity)}</Badge>{call.callType === "Call 2+" ? <Badge variant="outline" className="rounded-full border-slate-200 bg-slate-50 text-slate-700">Outcome: {humanize(call.outcome)}</Badge> : null}<MatchBadge label={call.callType === "Call 1" ? "Disposition" : "Outcome"} value={pair.outcomeMatch} /><MatchBadge label="Critical" value={pair.criticalMatch} /></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Main finding</div><p className="mt-2 text-sm font-semibold leading-6 text-slate-800">{call.mainFinding}</p></div><Link href={`/manager/rep-scoring/v6-1-calibration/call/${encodeURIComponent(pair.sourceRecordId)}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-red-700 hover:text-red-800">Review criteria and evidence <ArrowRight className="size-4" /></Link></article>; }
function RoundScore({ label, score, band }: { label: string; score: number | null; band?: string }) { return <div className="rounded-xl border border-slate-200 p-3"><div className="text-xs font-bold text-slate-500">{label}</div><div className="mt-1 text-2xl font-extrabold text-slate-950">{score === null ? "—" : score.toFixed(1)}</div><div className="text-xs text-slate-500">{band || "Pending"}</div></div>; }
function StabilityBadge({ pair }: { pair: V6CalibrationPair }) { const style = pair.actionStable === true ? "border-emerald-200 bg-emerald-50 text-emerald-800" : pair.actionStable === false ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-900"; const label = pair.actionStable === true ? `Stable · ${pair.delta?.toFixed(1)} pt` : pair.actionStable === false ? `Review · ${pair.delta?.toFixed(1) ?? "—"} pt` : "Second round pending"; return <Badge variant="outline" className={cn("rounded-full", style)}>{label}</Badge>; }
function MatchBadge({ label, value }: { label: string; value: boolean | null }) { const text = value === null ? `${label} pending` : value ? `${label} agrees` : `${label} differs`; return <Badge variant="outline" className={cn("rounded-full", value === false ? "border-red-200 bg-red-50 text-red-700" : "border-slate-200 bg-slate-50 text-slate-700")}>{text}</Badge>; }
function humanize(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDateTime(value: string) { if (!value) return "Date unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "America/New_York" }).format(date); }
