const {test}=require('node:test'),assert=require('node:assert/strict');
const {splitSentences,coachingSentenceSpans,dedupeRepeatedSentencesText,coachingRepairAfter}=require('./text-integrity.cjs');
const {attachReconciliationPrecheck}=require('./reconciliation-precheck.cjs');
const cite='[00:10:47.120, 00:12:14.550, 00:25:23.570]';
test('citation group stays intact with the observation',()=>{const s=splitSentences('You asked a useful question. '+cite+' This clarified the goal.');assert.equal(s.length,2);assert.ok(s[0].endsWith(cite));});
test('numbered strengths, decimals and paragraph boundaries survive',()=>{const x='1. You discussed $2.50 and asked a question. '+cite+' This helped.\n\n2. You explained the next step. [00:30:10.670] This clarified timing.';assert.equal(dedupeRepeatedSentencesText(x),x);assert.ok(splitSentences(x)[0].startsWith('You'));});
test('duplicate removal preserves all other characters and structure',()=>{const x='1. You asked a question. '+cite+' This helped. This helped.\n\n2. You asked another question. [00:30:10.670]';const out=dedupeRepeatedSentencesText(x);assert.ok(out.includes('\n\n2.'));assert.ok(out.includes(cite));assert.equal((out.match(/This helped\./g)||[]).length,1);});
test('repair retains original evidence, discards invented and repeated citations',()=>{assert.equal(coachingRepairAfter('You explained the amount. '+cite,'You clarified the amount. '+cite+' [09:59:59.999]'),'You clarified the amount. '+cite);assert.equal(coachingRepairAfter('Unsafe text. '+cite,''),'');});
test('sentence segmentation never loses non-whitespace characters',()=>{for(const x of ['1. A short sentence.\n2. Yes!','Price $2.50, Dr. Smith and email@example.com. '+cite,'No punctuation at end','A? B! C.'])assert.equal(coachingSentenceSpans(x).map(s=>s.text).join('').replace(/\s/g,''),x.replace(/\s/g,''));});
const sources=['a','b','c'].map(automationKey=>({json:{automationKey}}));
const record=(key,status='Processed')=>({json:{id:'rec'+key,fields:{'Automation Key':key,'Processing Status':status,'Meeting Transcript Link':'url','Transcript Google Doc ID':'doc','Recording File ID':'file'}}});
test('three collapsed empty searches retain all three candidates',()=>{const r=attachReconciliationPrecheck(sources,[{json:{},pairedItem:[{item:0},{item:1},{item:2}]}]);assert.equal(r.length,3);assert.ok(r.every(x=>!x.json.reconciliationSkipExpensivePath));});
test('out of order and mixed search results match exact keys',()=>{const r=attachReconciliationPrecheck(sources,[record('c'),record('a','Needs Review')]);assert.deepEqual(r.map(x=>x.json.reconciliationSkipExpensivePath),[false,false,true]);assert.equal(r[0].json.reconciliationPrecheckRecordId,'reca');});
test('flattened Airtable records are recognized',()=>{const r=record('a');assert.equal(attachReconciliationPrecheck([sources[0]],[{json:{id:r.json.id,...r.json.fields}}])[0].json.reconciliationSkipExpensivePath,true);});
test('unknown, duplicate and missing keys fail closed',()=>{assert.throws(()=>attachReconciliationPrecheck(sources,[record('z')]));assert.throws(()=>attachReconciliationPrecheck(sources,[record('a'),record('a')]));assert.throws(()=>attachReconciliationPrecheck([{json:{}}],[{json:{}}]));assert.throws(()=>attachReconciliationPrecheck([sources[0],sources[0]],[{json:{}}]));assert.throws(()=>attachReconciliationPrecheck(sources,[{json:{error:'failed'}}]));});

test('duplicate repair prose retains the cited version',()=>{const x='This makes the offer useful. This makes the offer useful. '+cite; const out=dedupeRepeatedSentencesText(x);assert.equal(out,'This makes the offer useful. '+cite);});
