const {test}=require('node:test');const assert=require('node:assert/strict');
const {transcriptBlocks,renderCoaching,applyAudit,applyAuditConsensus}=require('./structured-coaching.cjs');
const blocks=transcriptBlocks('[00:01:00.000] Rep: The amount is explained.\n[00:02:00.000] Buyer: Please clarify that amount.');
const analysis=()=>({status:'completed',call_status:'scored',refusal_reason:null,outcome:{payment:'not_confirmed',summary:'No payment confirmed.',evidence_ids:['T0002']},payment_actions:[{action:'Amount explained.',evidence_ids:['T0001']}],strengths:[{observation:'Explained an amount.',why_useful:'Made the offer concrete.',evidence_ids:['T0001']}],improvements:[{priority:'material',observation:'Did not reclarify after the later question; an amount was already explained.',evidence_ids:['T0002'],counterevidence_ids:['T0001'],counterevidence_summary:'The amount was already stated.',possible_effect:'Could leave uncertainty.',better_action:'Clarify the amount.',example:'Invented promise: pay $1 next year.'}],blockers:[],next_steps:[]});
const audit=()=>({outcome_pass:true,rejected_strengths:[],rejected_improvements:[],rejected_examples:[],rejected_blockers:[],rejected_next_steps:[],findings:[],improvement_reviews:[{index:0,verdict:'keep',counterevidence_ids:['T0001'],reason:'Earlier explanation credited.'}]});
test('keeps later clarification distinct from an earlier explanation and excludes hypothetical promises',()=>{
 const r=renderCoaching(applyAudit(analysis(),audit(),blocks),blocks);assert.match(r.what_to_improve,/already explained/);assert.doesNotMatch(JSON.stringify(r),/pay \$1 next year/);assert.equal(r.coaching_tip,'Clarify the amount.');assert.match(r.what_made_this_close_work,/No completed payment/);
});
test('rejects hallucinated source references before rendering',()=>{const a=analysis();a.improvements[0].counterevidence_ids=['T9999'];assert.throws(()=>renderCoaching(a,blocks),/reference/)});
test('auditor can remove an invented fault without losing a supported strength',()=>{const a=audit();a.rejected_improvements=[0];a.improvement_reviews[0].verdict='reject';const r=renderCoaching(applyAudit(analysis(),a,blocks),blocks);assert.match(r.what_to_improve,/No material/);assert.match(r.biggest_strength,/Explained an amount/)});
test('fails closed on missing, conflicting or out-of-range audits',()=>{for(const mutate of [a=>a.outcome_pass=false,a=>a.improvement_reviews=[],a=>a.rejected_improvements=[0],a=>a.rejected_strengths=[9]]){const a=audit();mutate(a);assert.throws(()=>applyAudit(analysis(),a,blocks))}});
test('supports manual transcripts without timestamps and does not invent timestamps',()=>{const b=transcriptBlocks('Rep: An offer.\n\nBuyer: A question.');assert.equal(b.length,2);const r=renderCoaching(analysis(),b);assert.doesNotMatch(r.what_to_improve,/00:/)});
test('preserves refusal and rejects inconsistent eligibility states',()=>{const r=renderCoaching({status:'refused',call_status:'call_1',refusal_reason:'Discovery only.'},[]);assert.equal(r.status,'refused');const a=analysis();a.call_status='call_1';assert.throws(()=>renderCoaching(a,blocks))});

test('independent reviews use rejection union and never manufacture a finding',()=>{const a=analysis();a.improvements[0].priority='optional';const first=audit(),second=audit();second.rejected_improvements=[0];second.improvement_reviews[0].verdict='reject';const r=renderCoaching(applyAuditConsensus(a,first,second,blocks),blocks);assert.match(r.what_to_improve,/No material/);assert.match(r.biggest_strength,/Explained an amount/);});
